DROP TABLE discounts;
CREATE TABLE discounts( 
	discount_id		NUMBER GENERATED BY DEFAULT AS IDENTITY 
	,discount_name  varchar2(255) NOT NULL 
	,amount			NUMBER(3,1) NOT NULL
	,start_date		DATE NOT NULL 
	,expired_date	DATE NOT NULL 
);

INSERT INTO 
  DISCOUNTS (
  			discount_name,
  			amount,
  			start_date,
  			expired_date
  			)
  	VALUES (
  			'Spring Promotion',
  			9.5,
  			date '2022-05-01',
  			DATE '2022-05-31'
  			);
COMMIT;
SELECT *
FROM DISCOUNTS d ;


INSERT INTO 
  DISCOUNTS (
  			discount_name,
  			amount,
  			start_date,
  			expired_date
  			)
  	VALUES (
  			'summer Promotion',
  			10.5,
  			current_date,
  			DATE '2022-05-31'
  			);
COMMIT;
SELECT *
FROM DISCOUNTS d ;


CREATE TABLE PARTS(
	part_id		NUMBER		GENERATED BY DEFAULT AS IDENTITY 
	,part_name 	varchar(50)	NOT NULL
	,lead_time 	NUMBER(2,0) NOT NULL 
	,cost		NUMBER(9,2) NOT NULL 
	, status	NUMBER(1,0)	NOT NULL 
	,PRIMARY KEY (part_id)
	);


INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('sed dictum', 5, 134, 0);

INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('aed dictum', 5, 62, 1);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('bed dictum', 5, 64, 1);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('ced dictum', 5, 234, 1);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('ded dictum', 5, 334, 0);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('eed dictum', 5, 434, 0);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('fed dictum', 5, 534, 0);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('ged dictum', 5, 634, 1);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('hed dictum', 5, 734, 0);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('ied dictum', 5, 834, 0);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('jed dictum', 5, 934, 1);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('ked dictum', 5, 34, 0);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('med dictum', 5, 14, 0);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('ned dictum', 5, 24, 0);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('led dictum', 5, 44, 0);
INSERT INTO EZEN.PARTS(PART_NAME, LEAD_TIME, COST, STATUS)VALUES('zed dictum', 5, 54, 1);
commit;

select *
from parts
order by part_id
;

update parts
    set cost = 130
where part_id = 1
;


update parts
    set lead_time = 30
        ,cost = 120
        ,status = 1
where part_id = 5
;

commit;


update parts
    set cost = cost * 1.05
;

rollback;



























