
-- 문항 1
ALTER TABLE EZEN.TB_EMP ADD HEAD_WORK_YN CHAR(1) ;


-- 문항 2

SELECT A.EMP_NO 
	, (SELECT B.EMP_NAME  FROM TB_EMP B WHERE B.EMP_NO = A.EMP_NO) AS EMP_NAME 
	, AVG(A.PAY_AMT) AS AVG_PAY_AMT
FROM TB_SAL_HIS A
WHERE A.PAY_DE  BETWEEN '20190101' AND '20191231'
GROUP BY A.EMP_NO 
HAVING AVG(A.PAY_AMT) >= 4500000
ORDER BY A.EMP_NO ;




-- 문항 3




SELECT A.EMP_NO 
	, A.EMP_NAME 
	, A.ADDR 
	, A.DEPT_CD 
	, B.DEPT_NM 
	, C.CERTI_CD 
FROM TB_EMP A, TB_DEPT B, TB_EMP_CERTI C
WHERE A.DEPT_CD = B.DEPT_CD 
	AND A.EMP_NO = C.EMP_NO 
	AND A.ADDR LIKE '%수원%';




-- 문항 4

SELECT A.EMP_NO 
	, A.EMP_NAME 
	, A.DEPT_CD 
	, B.DEPT_NM 
	, C.CERTI_CD 
FROM TB_EMP A, TB_DEPT B, TB_EMP_CERTI C
WHERE A.DEPT_CD = B.DEPT_CD
	AND A.EMP_NO = C.EMP_NO  
	AND B.DEPT_NM = '지원팀';





-- 문항 5

SELECT
A.CERTI_CD
, A.CERTI_NM
, A.ISSUE_INSTI_NM
FROM TB_CERTI A
ORDER BY A.CERTI_CD ;



--문항 7

SELECT *
FROM TB_EMP
WHERE EMP_NO IS NULL;



--문항8 

SELECT (SELECT B.EMP_NAME  FROM TB_EMP B WHERE B.EMP_NO = A.EMP_NO)
	, A.PAY_AMT/3000
FROM TB_SAL_HIS A
WHERE A.PAY_AMT/3000 >= 5;



--문항9
SELECT A.EMP_NO 
	, (SELECT B.DEPT_CD  FROM TB_EMP B WHERE B.EMP_NO = A.EMP_NO) AS DEPT_CD  
	, ROUND(AVG(A.PAY_AMT),2) AS AVG_PAY_AMT
FROM TB_SAL_HIS A
GROUP BY A.EMP_NO 
HAVING ROUND(AVG(A.PAY_AMT),2)  > 0
ORDER BY AVG_PAY_AMT ;





SELECT A.DEPT_CD 
	, (SELECT B.DEPT_NM FROM TB_DEPT B WHERE B.DEPT_CD = A.DEPT_CD) AS DEPT_NM 
	, COUNT(*) AS "직원수"
FROM TB_EMP A
GROUP BY A.DEPT_CD
HAVING (COUNT(*)) >= 3
ORDER BY A.DEPT_CD ;


